In [2]:
import pandas as pd

In [19]:
raw_data_df = pd.read_csv('raw/cs-training.csv', index_col=0)
raw_data_df

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
149996,0,0.040674,74,0,0.225131,2100.0,4,0,1,0,0.0
149997,0,0.299745,44,0,0.716562,5584.0,4,0,1,0,2.0
149998,0,0.246044,58,0,3870.000000,NaN,18,0,1,0,0.0
149999,0,0.000000,30,0,0.000000,5716.0,4,0,0,0,0.0
150000,0,0.850283,64,0,0.249908,8158.0,8,0,2,0,0.0

In [20]:
def check_na():
    num_columns = len(raw_data_df.columns)

    for i in range(num_columns):
        count = raw_data_df.iloc[:,i].isna().sum()
        print(raw_data_df.columns[i], count, count / len(raw_data_df))
check_na()

SeriousDlqin2yrs 0 0.0
RevolvingUtilizationOfUnsecuredLines 0 0.0
age 0 0.0
NumberOfTime30-59DaysPastDueNotWorse 0 0.0
DebtRatio 0 0.0
MonthlyIncome 29731 0.19820666666666667
NumberOfOpenCreditLinesAndLoans 0 0.0
NumberOfTimes90DaysLate 0 0.0
NumberRealEstateLoansOrLines 0 0.0
NumberOfTime60-89DaysPastDueNotWorse 0 0.0
NumberOfDependents 3924 0.02616

Evidence of montlyincome
Get debt
Replace debt ratio with debt

In [21]:
raw_data_df = raw_data_df.dropna()
check_na()

SeriousDlqin2yrs 0 0.0
RevolvingUtilizationOfUnsecuredLines 0 0.0
age 0 0.0
NumberOfTime30-59DaysPastDueNotWorse 0 0.0
DebtRatio 0 0.0
MonthlyIncome 0 0.0
NumberOfOpenCreditLinesAndLoans 0 0.0
NumberOfTimes90DaysLate 0 0.0
NumberRealEstateLoansOrLines 0 0.0
NumberOfTime60-89DaysPastDueNotWorse 0 0.0
NumberOfDependents 0 0.0

In [23]:
raw_data_df.to_csv('give_me_credit_data.csv', index=False)

In [24]:
raw_data_df.columns

Index(['SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='object')

In [27]:
list(raw_data_df.min())

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [29]:
list(raw_data_df.max())
raw_data_df.max()

SeriousDlqin2yrs                              1.0
RevolvingUtilizationOfUnsecuredLines      50708.0
age                                         103.0
NumberOfTime30-59DaysPastDueNotWorse         98.0
DebtRatio                                 61106.5
MonthlyIncome                           3008750.0
NumberOfOpenCreditLinesAndLoans              58.0
NumberOfTimes90DaysLate                      98.0
NumberRealEstateLoansOrLines                 54.0
NumberOfTime60-89DaysPastDueNotWorse         98.0
NumberOfDependents                           20.0
dtype: float64

In [37]:
data_dict = {
    'name': ['SeriousDlqin2yrs', 'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
    'description': [
        'Person experienced 90 days past due delinquency or worse',
        'Total balance on credit cards and personal lines of credit except real estate and no installment debt like car loans divided by the sum of credit limits',
        'Age of borrower in years',
        'Number of times borrower has been 30-59 days past due but no worse in the last 2 years.',
        'Monthly debt payments, alimony,living costs divided by monthy gross income',
        'Monthly income',
        'Number of Open loans (installment like car loan or mortgage) and Lines of credit (e.g. credit cards)',
        'Number of times borrower has been 90 days or more past due.',
        'Number of mortgage and real estate loans including home equity lines of credit',
        'Number of times borrower has been 60-89 days past due but no worse in the last 2 years.',
        'Number of dependents in family excluding themselves (spouse, children etc.)'
                   ],
    'upper_bound': [1.0, 50708.0, 103.0, 98.0, 61106.5, 3008750.0, 58.0, 98.0, 54.0, 98.0, 20.0],
    'lower_bound': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
}

info_df = pd.DataFrame(data_dict)
info_df.to_csv('give_me_credit_info.csv', index=False)
info_df

,name,description,upper_bound,lower_bound
0,SeriousDlqin2yrs,Person experienced 90 days past due delinquenc...,1.0,0.0
1,RevolvingUtilizationOfUnsecuredLines,Total balance on credit cards and personal lin...,50708.0,0.0
2,age,Age of borrower in years,103.0,0.0
3,NumberOfTime30-59DaysPastDueNotWorse,Number of times borrower has been 30-59 days p...,98.0,0.0
4,DebtRatio,"Monthly debt payments, alimony,living costs di...",61106.5,0.0
5,MonthlyIncome,Monthly income,3008750.0,0.0
6,NumberOfOpenCreditLinesAndLoans,Number of Open loans (installment like car loa...,58.0,0.0
7,NumberOfTimes90DaysLate,Number of times borrower has been 90 days or m...,98.0,0.0
8,NumberRealEstateLoansOrLines,Number of mortgage and real estate loans inclu...,54.0,0.0
9,NumberOfTime60-89DaysPastDueNotWorse,Number of times borrower has been 60-89 days p...,98.0,0.0
10,NumberOfDependents,Number of dependents in family excluding thems...,20.0,0.0